### ISSUE TITLE
Keypad not working?

### ISSUE THREAD

**Issue by marcoXbresciani** [kbilsted/KeyboordUsage#4]
Even though the tracking is fine and statistics are computed, it seems that whole keypad keys do not display the coloured hotkey map at all.
Having the coloured hotkey map on that area might be useful to know whether to buy a new tenkey or tenkeyless board.

Try the new Dell SK-3205 tenkey configuration.

**Comment by kbilsted** [comment]
Thanks for reporting. I dont use keyboards with keypads. So i need to test. There should be scan codes to detect them

**Comment by marcoXbresciani** [comment]
Codes seems detected, I see statistics increasing also with Num8, Add and other pad keys, but the graphics is not updated.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by marcoXbresciani** [comment]
It works, my mistake!

**Comment by Danita** [comment]
In my case it doesn't differentiate between main Enter key and keypad Enter key, which is one of the many reasons I'd like to try this program, as I'm trying to see if I can move from my 104 key layout to a TKL without losing too much functionality.
