### ISSUE TITLE
Can't add key without label

### ISSUE THREAD

**Issue by marcoXbresciani** [kbilsted/KeyboordUsage#6]
I've bought a Filco Majestouch 2 (see https://www.keyboardco.com/keyboard/italian-filco-majestouch-2-tenkeyless-nkr-click-action-keyboard.asp) and added two blank keycaps (see https://www.keyboardco.com/product/blank-windows-keys-2-keycaps-for-cherry-mx-switches.asp) to replace those with Windows logo but it seems that using neither `"Label1": ""` nor `"Label1": " "` is working. Not even using the &nbsp;

Moreover, if the configuration contains such labels, the application doesn't even open and there are no error messages whatsoever.

**Comment by kbilsted** [comment]
Thanks for reporting. Will look into it ;)

**Comment by kbilsted** [comment]
hi @marcoXbresciani  

I'm not entirely sure what you want to achieve? You want blank keys even though there is an underlying key? So if you buy https://www.amazon.com/Das-Keyboard-Ultimate-Mechanical-DAS4KULTMBLU/dp/B00JKQSGWE you want to display a keyboard also with all blank keys in keyboordusage ? How would that be useful?

Currently there is a validation that if you forget a displaylabel it fails. I should have notified the end user of the validation ;-)

**Comment by marcoXbresciani** [comment]
Hi,
  I've put the underscore on my keyboard configuration, otherwise I was not able to use it. But my win keys are actually blank. The idea is to let the user be able put either "" or " " for empty/blank keycaps.


Marco
________________________________

**Comment by kbilsted** [comment]
sure but why is it useful to have it blank?

**Comment by marcoXbresciani** [comment]
I bought those caps because I didn't want to see the win logo... :-)
________________________________

**Comment by kbilsted** [comment]
made improvements for v1.3
